### ISSUE TITLE
Specify depth level for opening at start

### ISSUE THREAD

**Issue by hacker1024** [laiiihz/json_view#11]
Hi,
Thanks for this brilliant package.
I'm displaying JSON data from an API. The base structure of every successful response is this:

```json
{
  "result": {},
  "stat": "ok"
}
```

I'd like the `JsonView` to open just one level at startup, so the first level of the `result` object can be seen.

For example:

Depth 0:

```
{
  "result": { ... },
  "stat": "ok"
}
```

Depth 1 (what I want):

```
{
  "result": {
    "breakfast": { ... },
    "lunch": { ... },
    "dinner": { ... }
  },
  "stat": "ok"
}
```

Depth 2:

```
{
  "result": {
    "breakfast": {
      "food": "Cereal",
      "drink": "Milk"
    },
    "lunch": {
      "food": "Sandwiches",
      "drink": "Juice"
    },
    "dinner": {
      "food": "Steak",
      "drink": "Wine"
    }
  },
  "stat": "ok"
}
```

etc.

**Comment by laiiihz** [comment]
great idea! I will add this feature😆

**Comment by laiiihz** [comment]
@hacker1024  version 0.4.0 has been released !

now can set default open depth in `JsonConfigData` , `JsonView` or `JsonViewBody` 

and i will close this issue for now.

* ConfigData
```dart
JsonConfigData(
  style: JsonStyleScheme(
    depth: 2,
  ),  
)
```

* JsonView
```dart
            JsonView(
              styleScheme: JsonStyleScheme(depth: 2),
              json: getJsonData(),
            ),
```

* JsonViewBody
```dart
            JsonViewBody(
              styleScheme: JsonStyleScheme(depth: 2),
              json: getJsonData(),
            ),
```
